"""Friction re-screen of the MNQ/MES/pairs combine graveyard — COMPLETE.

The ~17 buried combine candidates were killed by Topstep combine gates (win-rate
floor, >=1.0/day frequency, $2k trailing drawdown, worst-month guards). That is a
different question from *does this have an edge*. This re-scores them on economics.

THE SYSTEMATIC DEFECT: 17 of 18 studies hard-code COMMISSION = 4.80 round-trip and
model no slippage separately. Live MNQ books $2.00/ct RT (verified against the live
tape: trader-yank delta*$2*2ct minus logged pnl == -$4.00 on every clean trade).
Market/stop entries realistically pay ~$3.00 (commission + ~1 tick). The lone
exception is the pair-divergence survey, which costed properly at $1.24 RT plus an
explicit slippage-stress clause -- its numbers are already realistic.

Rows marked [rerun] were regenerated by re-running the study with COMMISSION=3.00.
Rows marked [derived] use the analytic re-scoring below (exact for EV, exact for PF).

Usage:  .venv/bin/python tools/friction_rescreen.py
"""

C_STUDY = 4.80   # what 17 of 18 studies assumed
C_MKT   = 3.00   # commission + ~1 tick spread: market/stop entries
C_LIMIT = 2.00   # live-verified booked commission, limit entries (YANK/gap-fade)

# name, N, freq/day, WR, PF@4.80, EV@4.80, PF@3.00, EV@3.00, note
# PF/EV@3.00 = None -> derived analytically; otherwise measured by re-running.
CANDS = [
 ("Volume Profile POC (VA70/TP=POC)", 6880, 23.09, .142, 1.010,   0.22, 1.10,  2.02, "rerun"),
 ("Pair MNQ-ES SHORT_A (thr30/sm1.0)",1181,  5.52, .560, 1.100,   2.06, 1.100, 2.06, "already @1.24"),
 ("Pair MNQ-ES SHORT_A (thr50/sm1.0)", 372,  1.74, .602, 1.419,  11.28, 1.419,11.28, "already @1.24"),
 ("Lunch-Window Oscillation",         1151,  3.88, .164, 0.750,  -4.28, 0.81, -2.48, "rerun"),
 ("ES/MNQ Stat Arb short [IS]",        350,  3.60, .578, 1.268,   6.45, None, None,  "derived"),
 ("ES/MNQ Stat Arb short [OOS]",       198,  3.60, .457, 0.765,  -7.70, None, None,  "derived"),
 ("HCVWAP v1 (1m, SD2.0/TP12)",        481,  1.61, .416, 0.810,  -1.83, None, None,  "derived"),
 ("HCVWAP v1 (1m, SD2.5/TP10)",        335,  1.12, .504, 0.920,  -0.66, None, None,  "derived"),
 ("HCVWAP v1 MES",                     258,  1.20, .329, 0.700,  -6.61, None, None,  "derived"),
 ("Pair MNQ-ES LONG_A (thr40/sm1.0)",  697,  3.26, .495, 0.795,  -6.35, 0.795,-6.35, "already @1.24"),
 ("PDH/PDL Breakout Momentum",         280,  0.94, .374, 0.796,  -8.45, None, None,  "derived"),
 ("5-min NQ Trend-Pullback",           200,  0.67, .354, 0.775,  -8.79, None, None,  "derived"),
 ("HCVWAP v2 (5m, SD2.5/S10)",         114,  0.38, .289, 1.280,   4.93, None, None,  "derived"),
 ("HCVWAP v2 (5m, SD2.0/S15) primary",  89,  0.30, .315, 1.290,   6.89, None, None,  "derived"),
 ("HCVWAP v2 (5m, SD2.0/S20)",          76,  0.26, .355, 1.300,   8.62, None, None,  "derived"),
 ("HCVWAP v3 long-only [OOS]",          10,  0.18, .300, 0.850,  -3.72, None, None,  "derived"),
 ("Vol Compression 1-min (CF.3/MB3)",   46,  0.15, .348, 1.460,   9.90, 1.58, 11.70, "rerun"),
 ("MES ORB Reversion v2 primary",       32,  0.15, .281, 0.700, -11.40, None, None,  "derived"),
 ("MES ORB Rev v2 (S12/ORB25)",         15,  0.07, .467, 1.360,  12.53, None, None,  "derived"),
 ("Vol Compression 15-min (CF.5/MB3)",  15,  0.05, .667, 1.770,  23.29, 1.84, 25.09, "rerun"),
]

# Volume Profile POC monthly P&L at COMMISSION=3.00 (from the re-run), for the
# concentration test: (month, N, avg_pnl)
POC_MONTHS = [
 ("2025-01",518,-1.09),("2025-02",558,-5.38),("2025-03",408,-6.42),("2025-04",572,-4.20),
 ("2025-05",489, 0.97),("2025-06",373, 7.92),("2025-07",538,-0.61),("2025-08",490,-2.60),
 ("2025-09",411,32.52),("2025-10",560,-3.39),("2025-11",429,-2.14),("2025-12",378,17.37),
 ("2026-01",535, 6.77),("2026-02",621,-0.16),
]

def rescore(N, w, pf, ev, c_old, c_new):
    ev_new = ev + (c_old - c_new)
    if abs(pf - 1.0) < 1e-9:
        return ev_new, float("nan")
    gl_net = ev * N / (pf - 1.0)
    gp_net = pf * gl_net
    gp_true = gp_net + w * N * c_old
    gl_true = gl_net - (1 - w) * N * c_old
    gp_n, gl_n = gp_true - w * N * c_new, gl_true + (1 - w) * N * c_new
    return ev_new, (gp_n / gl_n if gl_n > 0 else float("inf"))

print("=" * 122)
print("FRICTION RE-SCREEN (COMPLETE) — combine graveyard re-scored on economics, not combine gates")
print("=" * 122)
print("17 of 18 studies assumed COMMISSION=$4.80 RT with no separate slippage.")
print("Live MNQ books $2.00/ct RT. Market/stop entries realistically ~$3.00. Scored at $3.00 (conservative).")
print("Pair-divergence rows were already costed correctly at $1.24 RT + slippage stress -- shown unchanged.\n")

print(f"{'candidate':36}{'N':>6}{'/day':>7}{'WR':>7}{'EV@4.80':>9}{'PF@4.80':>8} |"
      f"{'EV@3.00':>9}{'PF@3.00':>8}{'ratio':>7}  verdict")
print("-" * 122)

rows = []
for name, N, fr, w, pf, ev, pf3i, ev3i, note in CANDS:
    if ev3i is None:
        ev3, pf3 = rescore(N, w, pf, ev, C_STUDY, C_MKT)
    else:
        ev3, pf3 = ev3i, pf3i
    ratio = ev3 / C_MKT
    v = ("LOSES TO FEES" if ev3 <= 0 else
         "CLEARS 3x"     if ratio >= 3 else
         "MARGINAL"      if ratio >= 1 else "THIN")
    rows.append((name, N, fr, w, ev, pf, ev3, pf3, ratio, v))
    print(f"{name:36}{N:>6}{fr:>7.2f}{w*100:>6.1f}%{ev:>9.2f}{pf:>8.3f} |"
          f"{ev3:>9.2f}{pf3:>8.3f}{ratio:>6.1f}x  {v}")

print("\n" + "=" * 122)
print("THE QUESTION: a candidate with s26-like frequency (>=1.0/day) that also survives its costs?")
print("=" * 122)
print(f"{'candidate':36}{'/day':>7}{'EV@3.00':>10}{'ratio':>8}{'days->N=300':>13}   qualifies?")
print("-" * 122)
qual = []
for name, N, fr, w, ev, pf, ev3, pf3, ratio, v in sorted(rows, key=lambda r: -r[2]):
    if fr < 1.0:
        continue
    q = "YES" if (ev3 > 0 and ratio >= 1.0) else ("positive, thin" if ev3 > 0 else "no")
    if ev3 > 0:
        qual.append(name)
    print(f"{name:36}{fr:>7.2f}{ev3:>10.2f}{ratio:>7.1f}x{300/fr:>13.0f}   {q}")

print("\n" + "=" * 122)
print("CONCENTRATION TEST — Volume Profile POC Fade, the only new high-frequency positive")
print("=" * 122)
tot = sum(n * a for _, n, a in POC_MONTHS)
ntot = sum(n for _, n, _ in POC_MONTHS)
print(f"  Total: N={ntot}  net=${tot:,.0f}  mean=${tot/ntot:.2f}/trade  (at $3.00 RT)\n")
print(f"  {'month':10}{'N':>6}{'avg$':>9}{'month net$':>13}{'% of total':>12}")
for m, n, a in POC_MONTHS:
    print(f"  {m:10}{n:>6}{a:>9.2f}{n*a:>13,.0f}{100*n*a/tot:>11.1f}%")
best = sorted(POC_MONTHS, key=lambda x: -x[1] * x[2])
for k in (1, 2, 3):
    drop = best[:k]
    rem_n = ntot - sum(n for _, n, _ in drop)
    rem = tot - sum(n * a for _, n, a in drop)
    print(f"\n  minus top {k} month(s) {[m for m,_,_ in drop]}: "
          f"N={rem_n}  net=${rem:,.0f}  mean=${rem/rem_n:+.2f}/trade")
neg = sum(1 for _, _, a in POC_MONTHS if a < 0)
print(f"\n  Months with negative mean P&L: {neg} of {len(POC_MONTHS)}")
