#!/usr/bin/env python
"""GAP-1 Friday promotion review (2026-07-04): direction-split check + live status.

Analysis-only. The sealed prereg (32da5d5, preregistration_gap_fade_panic_open.md)
forbids trading a direction-filtered variant; this script answers the 2026-07-01
watch item (is the backtest edge short-concentrated?) and reports live OOS status
against the sealed decision rule (N>=30 live AND >=30 days).

Reads (all read-only, main checkout):
  data/reports/gap_fade_20260625_205328.csv   sealed N=117 backtest per-trade output
  data/gap_fade/trades.csv                    live internal-sim trades (hash-chained)
  data/gap_fade/decisions.csv                 every 09:30 gap evaluation
  data/trades.db                              canonical trade DB (trader-gap-fade)
  logs/gap_fade_live.log                      best-effort realized TS SIM fills

Emits markdown to stdout.
"""
from __future__ import annotations

import re
import sqlite3
import sys
from math import isclose
from pathlib import Path

import pandas as pd

REPO = Path("/root/Silver-Bullet-ML-BMAD")
BACKTEST_CSV = REPO / "data/reports/gap_fade_20260625_205328.csv"
LIVE_TRADES = REPO / "data/gap_fade/trades.csv"
LIVE_DECISIONS = REPO / "data/gap_fade/decisions.csv"
TRADES_DB = REPO / "data/trades.db"
LIVE_LOG = REPO / "logs/gap_fade_live.log"

SEALED_N = 117
SEALED_PF = 1.761
LIVE_START = pd.Timestamp("2026-06-26")
REVIEW_DATE = pd.Timestamp("2026-07-04")


def pf(pnl: pd.Series) -> float:
    wins = pnl[pnl > 0].sum()
    losses = -pnl[pnl < 0].sum()
    return float("inf") if losses == 0 else wins / losses


def max_consec_losses(pnl: pd.Series) -> int:
    worst = run = 0
    for x in pnl:
        run = run + 1 if x < 0 else 0
        worst = max(worst, run)
    return worst


def stats_row(label: str, df: pd.DataFrame) -> str:
    pnl = df["pnl_usd"]
    n = len(df)
    wr = (pnl > 0).mean() * 100
    monthly = pnl.groupby(df["date"].str[:7]).sum()
    exits = df["outcome"].value_counts()
    exit_mix = "/".join(f"{exits.get(k, 0)}{k[0].upper()}" for k in ("time", "fill", "stop"))
    return (
        f"| {label} | {n} | {wr:.1f}% | {pf(pnl):.3f} | ${pnl.sum():,.0f} | "
        f"${pnl.mean():,.0f} | {max_consec_losses(pnl)} | "
        f"${monthly.min():,.0f} ({monthly.idxmin()}) | {exit_mix} |"
    )


def main() -> int:
    bt = pd.read_csv(BACKTEST_CSV)

    # --- Baseline reproduction gate (trust nothing until the sealed headline reproduces)
    got_pf = pf(bt["pnl_usd"])
    if len(bt) != SEALED_N or not isclose(got_pf, SEALED_PF, abs_tol=0.001):
        print(
            f"BASELINE REPRODUCTION FAILED: N={len(bt)} (want {SEALED_N}), "
            f"PF={got_pf:.4f} (want {SEALED_PF}) — aborting, splits not trustworthy.",
            file=sys.stderr,
        )
        return 1

    print("# GAP-1 direction-split review — generated by tools/gap1_direction_split_review.py")
    print()
    print(f"Baseline reproduction gate: PASS — N={len(bt)}, PF={got_pf:.3f} "
          f"(sealed: N={SEALED_N}, PF={SEALED_PF}).")
    print()

    header = ("| Slice | N | WR | PF | Net | Exp/trade | MaxConsecL | Worst month | "
              "Exits T/F/S |\n|---|---|---|---|---|---|---|---|---|")

    # --- Direction split (the watch-item question)
    print("## Sealed backtest (2025-01 → 2026-06-11 IS, 1ct gross) by direction")
    print()
    print(header)
    print(stats_row("ALL", bt))
    for side in ("long", "short"):
        print(stats_row(f"{side} (fade gap-{'down' if side == 'long' else 'up'})",
                        bt[bt["direction"] == side]))
    print()

    # --- Year x direction stability cross-check (descriptive only)
    print("## Year × direction (stability cross-check, descriptive only)")
    print()
    print(header)
    for year in ("2025", "2026"):
        ydf = bt[bt["date"].str.startswith(year)]
        print(stats_row(f"{year} ALL", ydf))
        for side in ("long", "short"):
            print(stats_row(f"{year} {side}", ydf[ydf["direction"] == side]))
    print()

    long_wr = (bt.loc[bt["direction"] == "long", "pnl_usd"] > 0).mean()
    print(f"Live-loss context: backtest long WR = {long_wr * 100:.1f}%, so the probability "
          f"that the first live LONG loses is ~{(1 - long_wr) * 100:.0f}% under the backtest "
          "distribution — a single long loss carries no degradation information.")
    print()

    # --- Live OOS status
    live = pd.read_csv(LIVE_TRADES)
    n_raw = len(live)
    live = live.drop_duplicates(subset=["date_et", "dir", "entry"]).reset_index(drop=True)
    print("## Live OOS (internal sim, TS SIM mirror; prospective from 2026-06-26)")
    print()
    if n_raw != len(live):
        print(f"Note: {n_raw - len(live)} duplicate row(s) dropped from trades.csv "
              "(06-25 double-entry before the entry guard; same trade, two chain hashes).")
        print()
    print("| Date | Dir | Gap% | Entry | Exit | Outcome | PnL |")
    print("|---|---|---|---|---|---|---|")
    for _, t in live.iterrows():
        print(f"| {t.date_et} | {t.dir} | {t.gap_pct:.2f}% | {t.entry} | {t.exit_px} "
              f"| {t.outcome} | ${t.pnl_usd:,.1f} |")
    live_pnl = live["pnl_usd"]
    print()
    print(f"Live totals: N={len(live)}, {int((live_pnl > 0).sum())}W/"
          f"{int((live_pnl <= 0).sum())}L, net ${live_pnl.sum():,.0f} modeled, "
          f"PF {pf(live_pnl):.3f}.")

    # Reconcile vs trades.db
    con = sqlite3.connect(TRADES_DB)
    db = pd.read_sql_query(
        "SELECT timestamp, direction, entry_price, exit_price, pnl FROM trades "
        "WHERE trader_id='trader-gap-fade' ORDER BY timestamp", con)
    con.close()
    match = len(db) == len(live) and isclose(db["pnl"].sum(), live_pnl.sum(), abs_tol=0.01)
    print(f"trades.db reconciliation: {len(db)} rows, net ${db['pnl'].sum():,.0f} — "
          f"{'MATCHES deduped trades.csv' if match else 'MISMATCH vs trades.csv — investigate'}.")
    print()

    # Decisions scan integrity + entry-rate projection
    dec = pd.read_csv(LIVE_DECISIONS)
    counts = dec["action"].value_counts().to_dict()
    sessions = dec["date_et"].nunique()
    entered_days = dec.loc[dec["action"] == "ENTERED", "date_et"].nunique()
    print(f"Decision log: {sessions} sessions scanned — " +
          ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + ".")
    rate = entered_days / sessions
    days_to_n30 = (30 - len(live)) / rate if rate > 0 else float("inf")
    # calendar days ≈ trading days x 7/5
    eta = REVIEW_DATE + pd.Timedelta(days=round(days_to_n30 * 7 / 5))
    print(f"Entry rate: {entered_days}/{sessions} sessions → at this rate the sealed "
          f"decision gate (N≥30 live) is reached ~{eta.date()} "
          f"(~{days_to_n30:.0f} more trading days). The 30-day clock alone is met "
          f"{(LIVE_START + pd.Timedelta(days=30)).date()}.")
    print()

    # --- Best-effort realized capture from the live log
    print("## Realized-vs-modeled capture (best effort)")
    print()
    if LIVE_LOG.exists():
        fill_lines = [ln.strip() for ln in LIVE_LOG.read_text(errors="ignore").splitlines()
                      if re.search(r"fill|Fill|FILLED", ln)]
        if fill_lines:
            print(f"{len(fill_lines)} fill-related log line(s) found in gap_fade_live.log "
                  "(inspect manually for realized fill prices):")
            print()
            print("```")
            for ln in fill_lines[-20:]:
                print(ln)
            print("```")
        else:
            print("No realized-fill confirmations found in gap_fade_live.log — the TS SIM "
                  "mirror's realized fill prices are NOT captured in structured form. "
                  "DATA GAP: promotion judgment must weight realized capture (per the "
                  "2026-06-29 gate), so realized-fill logging should be added before the "
                  "sealed decision point.")
    else:
        print("gap_fade_live.log not found — realized capture unavailable. DATA GAP (as above).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
