"""Glossary of trading terms used in the Silver Bullet system."""

GLOSSARY = {
    "MSS": """
**Market Structure Shift** - A reversal pattern in market structure where price breaks a key swing high or low, indicating a potential trend reversal. MSS is the primary pattern in the Silver Bullet setup and indicates institutional footprints entering the market.
    """,

    "Market Structure Shift": """
**Market Structure Shift** - A reversal pattern in market structure where price breaks a key swing high or low, indicating a potential trend reversal. MSS is the primary pattern in the Silver Bullet setup and indicates institutional footprints entering the market.
    """,

    "FVG": """
**Fair Value Gap** - A price imbalance between three consecutive candles where the wicks do not overlap, creating a "gap" in price action. FVGs represent areas where price moved too quickly and often act as support/resistance levels that price may revisit.
    """,

    "Fair Value Gap": """
**Fair Value Gap** - A price imbalance between three consecutive candles where the wicks do not overlap, creating a "gap" in price action. FVGs represent areas where price moved too quickly and often act as support/resistance levels that price may revisit.
    """,

    "ATR": """
**Average True Range** - A technical indicator measuring market volatility. ATR calculates the average range between high and low prices over a specified period (typically 14 periods). Higher ATR = higher volatility. Used in the Silver Bullet system to set stop-loss (1.2x ATR) and take-profit (2.5x ATR) levels.
    """,

    "Average True Range": """
**Average True Range** - A technical indicator measuring market volatility. ATR calculates the average range between high and low prices over a specified period (typically 14 periods). Higher ATR = higher volatility. Used in the Silver Bullet system to set stop-loss (1.2x ATR) and take-profit (2.5x ATR) levels.
    """,

    "Triple-Barrier": """
**Triple-Barrier Exit Strategy** - A risk management approach with three exit conditions:
1. **Upper Barrier**: Take-profit at 2.5x ATR above entry (for LONG) or below entry (for SHORT)
2. **Lower Barrier**: Stop-loss at 1.2x ATR below entry (for LONG) or above entry (for SHORT)
3. **Vertical Barrier**: Time-based exit at 45 minutes from entry

Position closes when ANY barrier is hit, ensuring defined risk and limited time exposure.
    """,

    "triple-barrier": """
**Triple-Barrier Exit Strategy** - A risk management approach with three exit conditions:
1. **Upper Barrier**: Take-profit at 2.5x ATR above entry (for LONG) or below entry (for SHORT)
2. **Lower Barrier**: Stop-loss at 1.2x ATR below entry (for LONG) or above entry (for SHORT)
3. **Vertical Barrier**: Time-based exit at 45 minutes from entry

Position closes when ANY barrier is hit, ensuring defined risk and limited time exposure.
    """,

    "Dollar Bars": """
**Dollar Bars** - A data aggregation method that creates a new bar every time a specified volume threshold is reached (e.g., $50M for MNQ futures). Unlike time-based bars (1-min, 5-min), Dollar Bars standardize by economic activity rather than time. This reduces noise during low-volume periods and captures information during high-volume periods.
    """,

    "Silver Bullet Setup": """
**Silver Bullet Setup** - A high-probability trading setup combining three key patterns:
1. **MSS (Market Structure Shift)**: Shows institutional footprints
2. **FVG (Fair Value Gap)**: Shows price imbalance
3. **Liquidity Sweep**: Shows stop-hunting activity

When all three patterns align (confluence), the probability of a successful trade increases significantly. The system adds ML meta-labeling to further filter and rank these setups.
    """,

    "Confidence Score": """
**Confidence Score** - A 1-5 star rating system based on pattern confluence:
- ★★★★★ (5 stars): MSS + FVG + Sweep + Time Window alignment
- ★★★★☆ (4 stars): MSS + FVG + Sweep
- ★★★☆☆ (3 stars): MSS + FVG
- ★★☆☆☆ (2 stars): MSS only
- ★☆☆☆☆ (1 star): Minimal confluence

Higher confidence scores indicate stronger setups with higher probability of success.
    """,

    "ML Probability": """
**ML Probability** - A prediction score (0-100%) generated by XGBoost meta-labeling model. The model was trained on 2+ years of historical MNQ data and analyzes 50+ features to predict the probability that a trade will be profitable. Signals below the minimum probability threshold are automatically filtered out.
    """,

    "Silver Bullet": """
**Silver Bullet Setup** - A high-probability trading setup combining three key patterns:
1. **MSS (Market Structure Shift)**: Shows institutional footprints
2. **FVG (Fair Value Gap)**: Shows price imbalance
3. **Liquidity Sweep**: Shows stop-hunting activity

When all three patterns align (confluence), the probability of a successful trade increases significantly. The system adds ML meta-labeling to further filter and rank these setups.
    """,

    "Time Windows": """
**Trading Time Windows** - Specific trading hours when the system is allowed to trade:
- **London AM**: 02:00-05:00 EST (European session opening)
- **NY AM**: 09:30-11:00 EST (US market opening)
- **NY PM**: 13:30-15:30 EST (US afternoon session)

These windows were identified through backtesting as having the highest win rates for the Silver Bullet setup. Signals outside these windows are automatically filtered.
    """,
}


def get_glossary_term(term: str) -> str:
    """Get glossary definition for a term.

    Args:
        term: Term to look up

    Returns:
        Definition of the term, or "Term not found" if missing
    """
    return GLOSSARY.get(term, "Term not found in glossary.")


def search_glossary(query: str) -> list:
    """Search glossary for terms matching query.

    Args:
        query: Search query string

    Returns:
        List of matching terms
    """
    query_lower = query.lower()
    matching_terms = []

    for term, definition in GLOSSARY.items():
        if query_lower in term.lower() or query_lower in definition.lower():
            matching_terms.append(term)

    return matching_terms
