"""Help content for all dashboard pages."""

# Table of contents for help navigation
HELP_TABLE_OF_CONTENTS = [
    ("Overview", "Overview page help"),
    ("Positions", "Positions page help"),
    ("Signals", "Signals page help"),
    ("Charts", "Charts page help"),
    ("Settings", "Settings page help"),
    ("Keyboard Shortcuts", "Keyboard shortcut reference"),
    ("Glossary", "Trading terms glossary"),
]

# Overview page help content
OVERVIEW_HELP = """
# Overview Page Help

## Account Metrics

### Account Equity
The total value of your trading account including all open positions and available cash.

### Daily P&L
Today's profit or loss in USD. Positive values (green) indicate profit, negative values (red) indicate loss.

### Win Rate
Percentage of winning trades today. Calculated as: (Winning Trades / Total Trades) × 100

### Drawdown
Current drawdown amount vs daily loss limit. Shows how close you are to hitting the daily loss limit.

### Open Positions
Number of currently open positions and total number of contracts.

### System Uptime
How long the trading system has been running since last restart.

## System Health

### API Status
Connection status to TradeStation API. Shows connected/disconnected and ping latency.

### Data Freshness
How recent the last market data update is. Stale data (>30 seconds) may indicate issues.

### Resource Usage
Current system resource utilization:
- **CPU**: Processor usage percentage
- **Memory**: RAM usage percentage
- **Disk**: Storage usage percentage

Green = healthy (<50%), Yellow = warning (50-80%), Red = critical (>80%)
"""

# Positions page help content
POSITIONS_HELP = """
# Positions Page Help

## Position Information

### Signal ID
Unique identifier for the signal that generated this position.

### Direction
Trade direction: LONG (📈) or SHORT (📉)

### Entry Price
The price at which the position was opened.

### Current Price
The current market price for MNQ futures.

### P&L ($)
Dollar profit or loss for this position. Green = profit, Red = loss.

### P&L (%)
Percentage profit or loss relative to entry price.

## Barrier Levels (Triple-Barrier Exit Strategy)

### Upper Barrier
Take-profit level at 2.5x ATR above entry. Position automatically exits if price hits this level.

### Lower Barrier
Stop-loss level at 1.2x ATR below entry (for LONG) or above entry (for SHORT). Position exits here to limit losses.

### Vertical Barrier
Time-based exit at 45 minutes from entry. Position automatically closes after this timeout to limit exposure.

## Barrier Progress

The progress bar shows how close price is to each barrier:
- **Upper bar**: Progress toward take-profit
- **Lower bar**: Progress toward stop-loss
- **Vertical bar**: Time remaining until 45-minute timeout

## Manual Exit

To manually close a position:
1. Click the "Exit" button next to the position
2. Enter your password when prompted
3. Click "Confirm Exit" to close the position

**Warning**: Manual exit bypasses the automated exit strategy and may result in suboptimal outcomes.
"""

# Signals page help content
SIGNALS_HELP = """
# Signals Page Help

## Signal Information

### Timestamp
When the signal was generated (HH:MM:SS format).

### Direction
Trade direction: LONG (📈) or SHORT (📉)

### Confidence
1-5 star rating based on pattern confluence:
- ★★★★★ (5 stars): Maximum confluence - MSS + FVG + Sweep + Time Window
- ★★★★☆ (4 stars): High confluence - MSS + FVG + Sweep
- ★★★☆☆ (3 stars): Medium confluence - MSS + FVG
- ★★☆☆☆ (2 stars): Low confluence - MSS only
- ★☆☆☆☆ (1 star): Minimal confluence

Higher confidence = higher probability of success.

### ML Probability
XGBoost meta-labeling prediction score (0-100%). Higher values indicate higher probability of trade success.

This score is generated by a machine learning model trained on 2+ years of historical MNQ data.

### Pattern Indicators

- **MSS Present**: ✓ if Market Structure Shift detected
- **FVG Present**: ✓ if Fair Value Gap detected
- **Sweep Present**: ✓ if Liquidity Sweep detected

Confluence of multiple patterns increases confidence.

### Time Window
Which trading time window this signal occurred in:
- **London AM**: 02:00-05:00 EST
- **NY AM**: 09:30-11:00 EST
- **NY PM**: 13:30-15:30 EST

Signals outside time windows are automatically filtered.

### Signal Status

- **🟢 Executed**: Trade was entered automatically
- **🟡 Filtered**: Signal filtered out (e.g., ML probability too low)
- **⚪ Rejected**: Signal rejected (e.g., outside time windows, risk limits)

## Filtering Signals

Use the filter controls to show only signals matching your criteria:
- **Status Filter**: All, Filtered, Executed, Rejected
- **Direction Filter**: All, LONG, SHORT
- **Confidence Filter**: All, 5★, 4★+, 3★+
"""

# Charts page help content
CHARTS_HELP = """
# Charts Page Help

## Dollar Bar Chart

The chart displays MNQ futures price data aggregated by Dollar Bars ($50M volume threshold).

### Chart Markers

- **▲ Green Triangle**: MSS Bullish (market structure shift upward)
- **▼ Red Triangle**: MSS Bearish (market structure shift downward)
- **🟣 Purple Circle**: Liquidity Sweep (large players hunting liquidity)
- **🔵 Blue Circle**: Trade Entry
- **✅ Green X**: Exit with Profit
- **❌ Red X**: Exit with Loss

### FVG Zones

Shaded rectangles showing Fair Value Gaps:
- **Green shaded**: Bullish FVG (price gap upward)
- **Red shaded**: Bearish FVG (price gap downward)

### Color Coding

- **Green candles**: Price moved up (close > open)
- **Red candles**: Price moved down (close < open)
- **Wick (shadow)**: Price range during the bar (high to low)

### Time Ranges

Select time range to view:
- **Hour**: Last 1 hour of data
- **Today**: All data from today's session
- **Week**: Last 7 days of data

### Chart Interactions

- **Hover**: See exact price and time data
- **Zoom**: Not currently supported (future enhancement)
- **Refresh**: Click "🔄 Refresh" to update chart
"""

# Settings page help content
SETTINGS_HELP = """
# Settings Page Help

## Risk Limits

### Daily Loss Limit
Maximum amount of loss allowed per day. Trading stops when this limit is reached.

**Recommended**: $500-$1000 for most accounts

**Trade-off**: Higher limits = more risk but more opportunity. Lower limits = safer but may miss profitable trades.

### Maximum Drawdown (%)
Maximum percentage drop from account peak allowed.

**Recommended**: 10-20%

**Trade-off**: Higher drawdown = can recover from larger losses but requires more capital to recover.

### Per-Trade Risk (%)
Maximum percentage of account equity risked per trade.

**Recommended**: 1-2%

**Trade-off**: Higher risk per trade = more profit potential but larger losses during losing streaks.

### Max Position (contracts)
Maximum number of MNQ contracts per position.

**Recommended**: 3-5 contracts

**Trade-off**: Larger positions = more profit potential but more risk exposure.

## Time Windows

Configure which trading hours are active:

### London AM (02:00-05:00 EST)
European session opening. High volatility but good trends.

### NY AM (09:30-11:00 EST)
US market opening. High volume and volatility.

### NY PM (13:30-15:30 EST)
US afternoon session. Lower volatility, tends to trend.

## ML Configuration

### Minimum Probability Threshold
Signals below this ML probability score are automatically filtered.

**Recommended**: 0.60-0.75

**Trade-off**: Higher threshold = fewer but higher quality trades. Lower threshold = more trades but lower win rate.

## Saving Changes

Any changes require password confirmation to prevent accidental modifications.

**Default values** are shown for reference.
"""

# Keyboard shortcuts help content
KEYBOARD_SHORTCUTS_HELP = """
# ⌨️ Keyboard Shortcuts

Keyboard shortcuts provide quick access to common dashboard actions. Use them to navigate faster and respond quickly to market conditions.

## 🔐 Emergency Shortcuts (Password Required)

These shortcuts require your emergency password for security. After 5 failed attempts, the account locks for 30 minutes.

### Ctrl+E - Emergency Stop
**⛔ Halt all trading activity immediately**

Use this when:
- You detect a critical system error
- Market conditions are extremely unfavorable
- You need to immediately stop all trading

**What happens:**
- Stops all signal generation
- Prevents new trade entries
- Existing positions remain open (use Ctrl+F to close them)

### Ctrl+F - Manual Flatten
**🔄 Close all open positions immediately**

Use this when:
- You want to exit all positions manually
- End of trading day
- Market volatility exceeds your risk tolerance

**What happens:**
- Submits market orders to close all positions
- Waits for fill confirmations
- Logs all closure actions to audit trail

**⚠️ Warning**: This action cannot be undone!

## 🧭 Navigation Shortcuts

These shortcuts let you quickly navigate between dashboard pages.

### Ctrl+S - Navigate to Settings
Jump directly to the Settings page to adjust risk limits, time windows, or ML configuration.

### Ctrl+P - Navigate to Positions
Jump directly to the Positions page to view open trades, P&L, and exit positions manually.

## 🛠️ Utility Shortcuts

Helper shortcuts for common dashboard actions.

### Ctrl+R - Refresh
Force immediate dashboard refresh, bypassing the 2-second auto-refresh timer.

**Use when:**
- You just executed a manual trade
- You need the latest market data
- You suspect data staleness

### Ctrl+L - Log Viewer
Open the log viewer modal to see recent system logs.

**Features:**
- Shows last 100 log lines
- Auto-refreshes every 2 seconds while open
- Filter by log level (ERROR, WARNING, INFO)
- Useful for debugging and monitoring

### F1 - Context-Sensitive Help
Open help modal for the current page.

**Smart help:**
- Automatically detects which page you're on
- Shows relevant help for that page
- Includes glossary of trading terms
- Press **ESC** to close

### ESC - Close Modal
Close any currently open modal or dialog.

**Closes:**
- Help modal (F1)
- Log viewer (Ctrl+L)
- Password prompt
- Any other dialog

**Tip**: Press ESC multiple times if you have nested modals open.

## 💡 Pro Tips

1. **Emergency Response**: Memorize Ctrl+E and Ctrl+F for quick emergency response
2. **Fast Navigation**: Use Ctrl+S and Ctrl+P to quickly switch between Settings and Positions
3. **Stay Informed**: Press Ctrl+L anytime to check system logs
4. **Get Help**: Press F1 from any page for context-sensitive help
5. **Close Quickly**: Press ESC to close modals without using the mouse

## ⚠️ Security Notes

- Emergency shortcuts (Ctrl+E, Ctrl+F) require password authentication
- 5 failed password attempts lock the account for 30 minutes
- All shortcut activations are logged to the audit trail
- Password is never displayed or stored in logs

## 🔧 Customization

Keyboard shortcuts are currently fixed to ensure consistency and security. Future versions may support customizable shortcuts.
"""


def get_help_content(page: str) -> str:
    """Get help content for a specific page.

    Args:
        page: Page name (Overview, Positions, Signals, Charts, Settings, Keyboard Shortcuts)

    Returns:
        Markdown-formatted help content
    """
    help_map = {
        "Overview": OVERVIEW_HELP,
        "Positions": POSITIONS_HELP,
        "Signals": SIGNALS_HELP,
        "Charts": CHARTS_HELP,
        "Settings": SETTINGS_HELP,
        "Keyboard Shortcuts": KEYBOARD_SHORTCUTS_HELP,
    }

    return help_map.get(page, "Help content not found.")
