"""Opening Range Breakout strategy implementation.

This strategy trades breakouts from the first hour's opening range
with volume confirmation for momentum trading.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, time

from pydantic import BaseModel, Field, field_validator

from src.data.models import DollarBar
from src.detection.breakout_detector import BreakoutDetector, BreakoutEvent
from src.detection.opening_range_detector import OpeningRange, OpeningRangeDetector

logger = logging.getLogger(__name__)


@dataclass
class OpeningRangeSignal:
    """Signal generated by Opening Range Breakout strategy.

    Attributes:
        strategy_name: Name of the strategy
        entry_price: Entry price for the trade
        stop_loss: Stop loss price (at opposite OR boundary)
        take_profit: Take profit price (2:1 risk-reward)
        direction: "long" or "short"
        confidence: Confidence score (0.60-1.0 for OR Breakout)
        timestamp: Signal generation timestamp
        contributing_factors: Details about OR, breakout, volume
        expected_win_rate: Expected win rate (60-65% target)
    """

    strategy_name: str
    entry_price: float
    stop_loss: float
    take_profit: float
    direction: str  # "long" or "short"
    confidence: float
    timestamp: datetime
    contributing_factors: dict = field(default_factory=dict)
    expected_win_rate: float = 0.625  # 60-65% target

    def to_pydantic(self) -> "OpeningRangeSignalModel":
        """Convert to Pydantic model for validation."""
        return OpeningRangeSignalModel(
            strategy_name=self.strategy_name,
            entry_price=self.entry_price,
            stop_loss=self.stop_loss,
            take_profit=self.take_profit,
            direction=self.direction,
            confidence=self.confidence,
            timestamp=self.timestamp,
            contributing_factors=self.contributing_factors,
        )


class OpeningRangeSignalModel(BaseModel):
    """Pydantic model for Opening Range signal with validation."""

    strategy_name: str = Field(default="Opening Range Breakout", description="Strategy identifier")
    entry_price: float = Field(..., gt=0, description="Entry price")
    stop_loss: float = Field(..., gt=0, description="Stop loss price")
    take_profit: float = Field(..., gt=0, description="Take profit price")
    direction: str = Field(..., description="Trade direction: 'long' or 'short'")
    confidence: float = Field(..., ge=0.60, le=1.0, description="Confidence score (0.60-1.0)")
    timestamp: datetime = Field(..., description="Signal timestamp")
    contributing_factors: dict = Field(
        default_factory=dict,
        description="Details about OR, breakout, volume",
    )
    expected_win_rate: float = Field(default=0.625, description="Expected win rate")

    @field_validator("direction")
    @classmethod
    def direction_must_be_valid(cls, v: str) -> str:
        """Validate direction is either long or short."""
        if v not in ["long", "short"]:
            raise ValueError("direction must be 'long' or 'short'")
        return v

    @field_validator("stop_loss", "take_profit")
    @classmethod
    def prices_must_align_with_direction(
        cls, v: float, info
    ) -> float:  # type: ignore[no-untyped-def]
        """Validate stop loss and take profit are appropriate for direction."""
        direction = info.data.get("direction")
        entry = info.data.get("entry_price")

        if entry is None or direction is None:
            return v

        if direction == "long":
            # For long: SL should be below entry, TP should be above
            field_name = "stop_loss" if "stop" in str(info.field_name) else "take_profit"
            if field_name == "stop_loss" and v >= entry:
                raise ValueError("stop_loss must be below entry_price for long")
            if field_name == "take_profit" and v <= entry:
                raise ValueError("take_profit must be above entry_price for long")
        else:  # short
            # For short: SL should be above entry, TP should be below
            field_name = "stop_loss" if "stop" in str(info.field_name) else "take_profit"
            if field_name == "stop_loss" and v <= entry:
                raise ValueError("stop_loss must be above entry_price for short")
            if field_name == "take_profit" and v >= entry:
                raise ValueError("take_profit must be below entry_price for short")

        return v

    @field_validator("take_profit")
    @classmethod
    def validate_risk_reward_ratio(cls, v: float, info) -> float:  # type: ignore[no-untyped-def]
        """Validate 2:1 risk-reward ratio."""
        entry = info.data.get("entry_price")
        stop_loss = info.data.get("stop_loss")
        direction = info.data.get("direction")

        if entry is None or stop_loss is None or direction is None:
            return v

        risk = abs(entry - stop_loss)
        reward = abs(v - entry)

        if risk == 0:
            return v

        ratio = reward / risk

        # Allow some tolerance for rounding
        if ratio < 1.9:
            raise ValueError(f"take_profit must provide at least 2:1 reward-risk ratio (current: {ratio:.2f})")

        return v


class OpeningRangeStrategy:
    """Opening Range Breakout strategy for first-hour momentum trading.

    Entry Conditions:
    - LONG: Breakout above ORH with volume > 1.5x baseline
    - SHORT: Breakout below ORL with volume > 1.5x baseline

    Risk Management:
    - Stop loss: At opposite OR boundary (ORL for long, ORH for short)
    - Take profit: 2:1 reward-risk ratio
    - Confidence: 0.60-0.90 based on breakout strength

    Attributes:
        _or_detector: Tracks opening range (9:30-10:30 AM ET)
        _breakout_detector: Detects breakouts with volume confirmation
        _or_start: Opening range start time
        _or_end: Opening range end time
    """

    DEFAULT_OR_START = time(9, 30)
    DEFAULT_OR_END = time(10, 30)
    DEFAULT_TIMEZONE = "America/New_York"

    def __init__(
        self,
        config: dict | None = None,
    ) -> None:
        """Initialize Opening Range Breakout strategy.

        Args:
            config: Optional configuration dictionary:
                - or_start: Opening range start time (default 9:30)
                - or_end: Opening range end time (default 10:30)
                - tick_size: Contract tick size (default 0.25)
                - volume_threshold: Volume multiplier (default 1.5)
        """
        config = config or {}

        or_start = config.get("or_start", self.DEFAULT_OR_START)
        or_end = config.get("or_end", self.DEFAULT_OR_END)
        timezone = config.get("timezone", self.DEFAULT_TIMEZONE)

        self._or_detector = OpeningRangeDetector(
            or_start=or_start, or_end=or_end, timezone=timezone
        )

        tick_size = config.get("tick_size", 0.25)
        volume_threshold = config.get("volume_threshold", 1.5)

        self._breakout_detector = BreakoutDetector(
            tick_size=tick_size, volume_threshold=volume_threshold
        )

    def process_bar(self, bar: DollarBar) -> OpeningRangeSignal | None:
        """Process a dollar bar and generate signal if breakout detected.

        Args:
            bar: Current dollar bar to process

        Returns:
            OpeningRangeSignal if breakout detected, None otherwise
        """
        # Update opening range detector
        self._or_detector.process_bar(bar)

        # Get current opening range
        opening_range = self._or_detector.get_opening_range()

        if opening_range is None or not opening_range.is_complete:
            # Opening range not yet established
            return None

        # Check for breakout
        breakout = self._breakout_detector.detect_breakout(bar, opening_range)

        if breakout is None:
            return None

        # Generate signal from breakout
        signal = self._generate_signal(breakout, opening_range)

        logger.info(
            f"Opening Range {signal.direction.upper()} signal: "
            f"entry {signal.entry_price:.2f}, "
            f"confidence {signal.confidence:.2f}"
        )

        return signal

    def _generate_signal(
        self, breakout: BreakoutEvent, opening_range: OpeningRange
    ) -> OpeningRangeSignal:
        """Generate trading signal from breakout event.

        Args:
            breakout: Breakout event
            opening_range: Opening range data

        Returns:
            OpeningRangeSignal with entry, SL, TP
        """
        if breakout.direction == "bullish":
            return self._generate_long_signal(breakout, opening_range)
        else:
            return self._generate_short_signal(breakout, opening_range)

    def _generate_long_signal(
        self, breakout: BreakoutEvent, opening_range: OpeningRange
    ) -> OpeningRangeSignal:
        """Generate LONG signal for bullish breakout.

        Args:
            breakout: Bullish breakout event
            opening_range: Opening range data

        Returns:
            OpeningRangeSignal for long entry
        """
        # Entry: Breakout price or current close
        entry = breakout.bar.close

        # Stop loss: At ORL (opposite boundary)
        stop_loss = opening_range.low

        # Take profit: 2:1 reward-risk ratio
        risk = entry - stop_loss
        take_profit = entry + (2.0 * risk)

        # Confidence: Base 0.60 + volume strength
        confidence = 0.60
        confidence += min(0.20, (breakout.volume_ratio - 1.5) / 5)  # Volume bonus
        confidence = min(0.90, confidence)  # Cap at 0.90

        signal = OpeningRangeSignal(
            strategy_name="Opening Range Breakout",
            entry_price=entry,
            stop_loss=stop_loss,
            take_profit=take_profit,
            direction="long",
            confidence=confidence,
            timestamp=breakout.timestamp,
            contributing_factors={
                "orh": opening_range.high,
                "orl": opening_range.low,
                "breakout_price": breakout.breakout_price,
                "volume_ratio": breakout.volume_ratio,
                "or_size": opening_range.high - opening_range.low,
            },
        )

        return signal

    def _generate_short_signal(
        self, breakout: BreakoutEvent, opening_range: OpeningRange
    ) -> OpeningRangeSignal:
        """Generate SHORT signal for bearish breakout.

        Args:
            breakout: Bearish breakout event
            opening_range: Opening range data

        Returns:
            OpeningRangeSignal for short entry
        """
        # Entry: Breakout price or current close
        entry = breakout.bar.close

        # Stop loss: At ORH (opposite boundary)
        stop_loss = opening_range.high

        # Take profit: 2:1 reward-risk ratio
        risk = stop_loss - entry
        take_profit = entry - (2.0 * risk)

        # Confidence: Base 0.60 + volume strength
        confidence = 0.60
        confidence += min(0.20, (breakout.volume_ratio - 1.5) / 5)  # Volume bonus
        confidence = min(0.90, confidence)  # Cap at 0.90

        signal = OpeningRangeSignal(
            strategy_name="Opening Range Breakout",
            entry_price=entry,
            stop_loss=stop_loss,
            take_profit=take_profit,
            direction="short",
            confidence=confidence,
            timestamp=breakout.timestamp,
            contributing_factors={
                "orh": opening_range.high,
                "orl": opening_range.low,
                "breakout_price": breakout.breakout_price,
                "volume_ratio": breakout.volume_ratio,
                "or_size": opening_range.high - opening_range.low,
            },
        )

        return signal
