"""VWAP Bounce strategy implementation.

This strategy trades pullbacks to VWAP in trending markets using:
1. VWAP calculation for dynamic support/resistance level
2. Rejection candle detection at VWAP
3. ADX trend filter to confirm trending market
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime

from pydantic import BaseModel, Field, field_validator

from src.data.models import DollarBar
from src.detection.adx_calculator import ADXCalculator, ADXResult
from src.detection.rejection_detector import RejectionDetector, RejectionEvent
from src.detection.vwap_calculator import VWAPCalculator

logger = logging.getLogger(__name__)


@dataclass
class VWAPBounceSignal:
    """Signal generated by VWAP Bounce strategy.

    Attributes:
        strategy_name: Name of the strategy
        entry_price: Entry price for the trade
        stop_loss: Stop loss price
        take_profit: Take profit price (2:1 risk-reward)
        direction: "long" or "short"
        confidence: Confidence score (0.65-1.0 for VWAP Bounce)
        timestamp: Signal generation timestamp
        contributing_factors: Details about rejection, ADX, VWAP
        expected_win_rate: Expected win rate (65-70% target)
    """

    strategy_name: str
    entry_price: float
    stop_loss: float
    take_profit: float
    direction: str  # "long" or "short"
    confidence: float
    timestamp: datetime
    contributing_factors: dict = field(default_factory=dict)
    expected_win_rate: float = 0.675  # 65-70% target

    def to_pydantic(self) -> "VWAPBounceSignalModel":
        """Convert to Pydantic model for validation."""
        return VWAPBounceSignalModel(
            strategy_name=self.strategy_name,
            entry_price=self.entry_price,
            stop_loss=self.stop_loss,
            take_profit=self.take_profit,
            direction=self.direction,
            confidence=self.confidence,
            timestamp=self.timestamp,
            contributing_factors=self.contributing_factors,
        )


class VWAPBounceSignalModel(BaseModel):
    """Pydantic model for VWAP Bounce signal with validation.

    Provides runtime validation for signal data.
    """

    strategy_name: str = Field(default="VWAP Bounce", description="Strategy identifier")
    entry_price: float = Field(..., gt=0, description="Entry price")
    stop_loss: float = Field(..., gt=0, description="Stop loss price")
    take_profit: float = Field(..., gt=0, description="Take profit price")
    direction: str = Field(..., description="Trade direction: 'long' or 'short'")
    confidence: float = Field(..., ge=0.65, le=1.0, description="Confidence score (0.65-1.0)")
    timestamp: datetime = Field(..., description="Signal timestamp")
    contributing_factors: dict = Field(
        default_factory=dict,
        description="Details about rejection, ADX, VWAP alignment",
    )
    expected_win_rate: float = Field(default=0.675, description="Expected win rate")

    @field_validator("direction")
    @classmethod
    def direction_must_be_valid(cls, v: str) -> str:
        """Validate direction is either long or short."""
        if v not in ["long", "short"]:
            raise ValueError("direction must be 'long' or 'short'")
        return v

    @field_validator("stop_loss", "take_profit")
    @classmethod
    def prices_must_align_with_direction(
        cls, v: float, info
    ) -> float:  # type: ignore[no-untyped-def]
        """Validate stop loss and take profit are appropriate for direction."""
        direction = info.data.get("direction")
        entry = info.data.get("entry_price")

        if entry is None or direction is None:
            return v

        if direction == "long":
            # For long: SL should be below entry, TP should be above
            field_name = "stop_loss" if "stop" in str(info.field_name) else "take_profit"
            if field_name == "stop_loss" and v >= entry:
                raise ValueError("stop_loss must be below entry_price for long")
            if field_name == "take_profit" and v <= entry:
                raise ValueError("take_profit must be above entry_price for long")
        else:  # short
            # For short: SL should be above entry, TP should be below
            field_name = "stop_loss" if "stop" in str(info.field_name) else "take_profit"
            if field_name == "stop_loss" and v <= entry:
                raise ValueError("stop_loss must be above entry_price for short")
            if field_name == "take_profit" and v >= entry:
                raise ValueError("take_profit must be below entry_price for short")

        return v

    @field_validator("take_profit")
    @classmethod
    def validate_risk_reward_ratio(cls, v: float, info) -> float:  # type: ignore[no-untyped-def]
        """Validate 2:1 risk-reward ratio."""
        entry = info.data.get("entry_price")
        stop_loss = info.data.get("stop_loss")
        direction = info.data.get("direction")

        if entry is None or stop_loss is None or direction is None:
            return v

        risk = abs(entry - stop_loss)
        reward = abs(v - entry)

        if risk == 0:
            return v

        ratio = reward / risk

        # Allow some tolerance for rounding
        if ratio < 1.9:  # Slightly under 2:1 for rounding tolerance
            raise ValueError(f"take_profit must provide at least 2:1 reward-risk ratio (current: {ratio:.2f})")

        return v


class VWAPBounceStrategy:
    """VWAP Bounce strategy for pullback trading in trending markets.

    Entry Conditions:
    - LONG: Bullish rejection below VWAP + ADX > 20 + DI+ > DI-
    - SHORT: Bearish rejection above VWAP + ADX > 20 + DI- > DI+

    Risk Management:
    - Stop loss: 1.0× ATR or rejection low/high
    - Take profit: 2:1 reward-risk ratio
    - Confidence: 0.70-0.95 based on signal strength

    Attributes:
        _vwap_calculator: Calculates session VWAP
        _rejection_detector: Detects rejection candles at VWAP
        _adx_calculator: Calculates ADX trend filter
        _lookback_period: Bars to look back for calculations
        _adx_threshold: Minimum ADX for trending market
    """

    DEFAULT_LOOKBACK_PERIOD = 30
    DEFAULT_ADX_THRESHOLD = 20
    DEFAULT_MIN_ADX = 20
    DEFAULT_ATR_PERIOD = 14

    def __init__(
        self,
        config: dict | None = None,
    ) -> None:
        """Initialize VWAP Bounce strategy.

        Args:
            config: Optional configuration dictionary with parameters:
                - lookback_period: Bars for calculations (default 30)
                - adx_threshold: Minimum ADX for trending (default 20)
                - tick_size: Contract tick size (default 0.25 for MNQ)
                - rejection_threshold: Volume multiplier for rejection (default 1.2)
        """
        config = config or {}

        self._lookback_period = config.get("lookback_period", self.DEFAULT_LOOKBACK_PERIOD)
        adx_threshold = config.get("adx_threshold", self.DEFAULT_ADX_THRESHOLD)

        self._vwap_calculator = VWAPCalculator()
        self._rejection_detector = RejectionDetector(
            tick_size=config.get("tick_size", 0.25),
            volume_threshold=config.get("rejection_threshold", 1.2),
        )
        self._adx_calculator = ADXCalculator(adx_threshold=adx_threshold)

        # Store historical bars for calculations
        self._historical_bars: list[DollarBar] = []

        # ATR for stop loss calculation
        self._atr_period = config.get("atr_period", self.DEFAULT_ATR_PERIOD)
        self._atr_values: list[float] = []

    def process_bar(self, bar: DollarBar) -> VWAPBounceSignal | None:
        """Process a dollar bar and generate signal if conditions met.

        Args:
            bar: Current dollar bar to process

        Returns:
            VWAPBounceSignal if conditions met, None otherwise
        """
        # Add bar to history
        self._historical_bars.append(bar)

        # Keep only necessary lookback
        if len(self._historical_bars) > self._lookback_period:
            self._historical_bars = self._historical_bars[-self._lookback_period :]

        # Need minimum bars for calculations
        if len(self._historical_bars) < 20:
            return None

        # Calculate VWAP
        vwap = self._vwap_calculator.calculate_vwap([bar])

        if vwap == 0:
            return None

        # Calculate ADX for trend filter
        adx_result = self._adx_calculator.calculate_adx(self._historical_bars)

        if adx_result is None:
            return None

        # Filter: Only trade in trending markets (ADX > threshold)
        if adx_result.adx <= self._adx_calculator._adx_threshold:
            logger.debug(f"ADX {adx_result.adx:.2f} below threshold {self._adx_calculator._adx_threshold}")
            return None

        # Detect rejection at VWAP
        rejection = self._rejection_detector.detect_rejection(
            bar, vwap, self._historical_bars[:-1]
        )

        if rejection is None:
            return None

        # Check signal confluence: rejection + ADX trend direction alignment
        signal = self._check_signal_confluence(rejection, adx_result, bar, vwap)

        if signal:
            logger.info(
                f"VWAP Bounce {signal.direction.upper()} signal: "
                f"entry {signal.entry_price:.2f}, "
                f"confidence {signal.confidence:.2f}"
            )

        return signal

    def _check_signal_confluence(
        self,
        rejection: RejectionEvent,
        adx_result: ADXResult,
        bar: DollarBar,
        vwap: float,
    ) -> VWAPBounceSignal | None:
        """Check if rejection and ADX trend align for signal.

        Args:
            rejection: Rejection event
            adx_result: ADX calculation result
            bar: Current bar
            vwap: Current VWAP value

        Returns:
            VWAPBounceSignal if conditions align, None otherwise
        """
        # LONG: Bullish rejection + uptrend (DI+ > DI-)
        if rejection.rejection_type == "bullish" and adx_result.trend_direction == "up":
            return self._generate_long_signal(rejection, adx_result, bar, vwap)

        # SHORT: Bearish rejection + downtrend (DI- > DI+)
        if rejection.rejection_type == "bearish" and adx_result.trend_direction == "down":
            return self._generate_short_signal(rejection, adx_result, bar, vwap)

        # No alignment
        return None

    def _generate_long_signal(
        self,
        rejection: RejectionEvent,
        adx_result: ADXResult,
        bar: DollarBar,
        vwap: float,
    ) -> VWAPBounceSignal:
        """Generate LONG signal for bullish rejection in uptrend.

        Args:
            rejection: Bullish rejection event
            adx_result: ADX result showing uptrend
            bar: Current bar
            vwap: VWAP value

        Returns:
            VWAPBounceSignal for long entry
        """
        # Entry: Current close or next bar open
        entry = bar.close

        # Stop loss: Use ATR or rejection low
        atr = self._calculate_atr()
        stop_loss = max(rejection.bar.low, entry - atr)

        # Take profit: 2:1 reward-risk ratio
        risk = entry - stop_loss
        take_profit = entry + (2.0 * risk)

        # Confidence: Base 0.70 + adjustments
        confidence = 0.70
        confidence += min(0.10, (adx_result.adx - 20) / 100)  # ADX strength
        confidence += min(0.10, (rejection.volume_ratio - 1.0) / 10)  # Volume confirmation
        confidence = min(0.95, confidence)  # Cap at 0.95

        signal = VWAPBounceSignal(
            strategy_name="VWAP Bounce",
            entry_price=entry,
            stop_loss=stop_loss,
            take_profit=take_profit,
            direction="long",
            confidence=confidence,
            timestamp=bar.timestamp,
            contributing_factors={
                "rejection_type": rejection.rejection_type,
                "vwap_value": vwap,
                "adx": adx_result.adx,
                "di_plus": adx_result.di_plus,
                "di_minus": adx_result.di_minus,
                "volume_ratio": rejection.volume_ratio,
                "atr": atr,
            },
        )

        return signal

    def _generate_short_signal(
        self,
        rejection: RejectionEvent,
        adx_result: ADXResult,
        bar: DollarBar,
        vwap: float,
    ) -> VWAPBounceSignal:
        """Generate SHORT signal for bearish rejection in downtrend.

        Args:
            rejection: Bearish rejection event
            adx_result: ADX result showing downtrend
            bar: Current bar
            vwap: VWAP value

        Returns:
            VWAPBounceSignal for short entry
        """
        # Entry: Current close or next bar open
        entry = bar.close

        # Stop loss: Use ATR or rejection high
        atr = self._calculate_atr()
        stop_loss = min(rejection.bar.high, entry + atr)

        # Take profit: 2:1 reward-risk ratio
        risk = stop_loss - entry
        take_profit = entry - (2.0 * risk)

        # Confidence: Base 0.70 + adjustments
        confidence = 0.70
        confidence += min(0.10, (adx_result.adx - 20) / 100)  # ADX strength
        confidence += min(0.10, (rejection.volume_ratio - 1.0) / 10)  # Volume confirmation
        confidence = min(0.95, confidence)  # Cap at 0.95

        signal = VWAPBounceSignal(
            strategy_name="VWAP Bounce",
            entry_price=entry,
            stop_loss=stop_loss,
            take_profit=take_profit,
            direction="short",
            confidence=confidence,
            timestamp=bar.timestamp,
            contributing_factors={
                "rejection_type": rejection.rejection_type,
                "vwap_value": vwap,
                "adx": adx_result.adx,
                "di_plus": adx_result.di_plus,
                "di_minus": adx_result.di_minus,
                "volume_ratio": rejection.volume_ratio,
                "atr": atr,
            },
        )

        return signal

    def _calculate_atr(self) -> float:
        """Calculate Average True Range for stop loss.

        Returns:
            ATR value using configured period
        """
        if len(self._historical_bars) < self._atr_period + 1:
            # Default ATR if insufficient bars
            return 10.0

        recent_bars = self._historical_bars[-self._atr_period :]

        true_ranges = []
        for i in range(1, len(recent_bars)):
            high = recent_bars[i].high
            low = recent_bars[i].low
            prev_close = recent_bars[i - 1].close

            tr = max(high - low, abs(high - prev_close), abs(low - prev_close))
            true_ranges.append(tr)

        if not true_ranges:
            return 10.0

        return sum(true_ranges) / len(true_ranges)
